## Creating dataframes

In [1]:
import pandas as pd

In [2]:
#from python list
data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]
df=pd.DataFrame(data, columns=["Name","Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [3]:
#from Dictionary of lists
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}
df=pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [6]:
#from Numpy array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [7]:
#from xlsx file
df=pd.read_excel("data.xlsx")
print(df)

     Name  Age  Marks
0    Arya   21    100
1  Priyam   31     20
2     yug   23     23
3   harsh   34     34
4  tushar   89     28
5     het  100     67
6   bhavy   22     79

In [8]:
#from Csv file
df=pd.read_csv("data.csv")
print(df)

     Name  Age  Marks
0    Arya   21    100
1  Priyam   31     20
2     yug   23     23
3   harsh   34     34
4  tushar   89     28
5     het  100     67
6   bhavy   22     79

In [11]:
#from Json file
# df=pd.read_json("data.json")
# print(df)

In [12]:
#from the web(URL)
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
#EDA (Exploratory Data Analysis) for above dataframe
df.head()         # First 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
df.tail() #last 5 rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [15]:
df.info() # info about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [16]:
df.describe() #status of numeric columns

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [18]:
df.columns #list of column

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [20]:
df.shape #(rows,columns)

(244, 7)