## Data Cleaning & Preprocessing

In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("data_cleaning_sample.xlsx")

In [3]:
df

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie   NaN        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
3  Charlie   NaN        Delhi      M    charlie@example 2021-07-20
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5      NaN  28.0        Delhi      F     eve@domain.com        NaT
6    Alice  25.0     New York      F  alice@example.com 2021-05-01
7    Alice  25.0     New York      F  alice@example.com 2021-05-01
8  Charlie   NaN        Delhi      M    charlie@example 2021-07-20

In [4]:
df.isnull()              # True for NaNs

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [5]:
df.isnull().sum()        # Count missing per column

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [6]:
df.dropna() # Drop rows with *any* missing values

    Name   Age         City Gender              Email  Join Date
0  Alice  25.0     New York      F  alice@example.com 2021-05-01
2    Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
4  David  22.0       Mumbai      M  david@example.com 2019-11-12
6  Alice  25.0     New York      F  alice@example.com 2021-05-01
7  Alice  25.0     New York      F  alice@example.com 2021-05-01

In [7]:
df.dropna(axis=1) # Drop columns with missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [8]:
df.fillna(0) ## Replace NaN with 0

      Name   Age         City Gender              Email            Join Date
0    Alice  25.0     New York      F  alice@example.com  2021-05-01 00:00:00
1  Charlie   0.0        Delhi      M    charlie@example  2021-07-20 00:00:00
2      Bob  30.0  Los Angeles      M    bob@example.com  2020-06-15 00:00:00
3  Charlie   0.0        Delhi      M    charlie@example  2021-07-20 00:00:00
4    David  22.0       Mumbai      M  david@example.com  2019-11-12 00:00:00
5        0  28.0        Delhi      F     eve@domain.com                    0
6    Alice  25.0     New York      F  alice@example.com  2021-05-01 00:00:00
7    Alice  25.0     New York      F  alice@example.com  2021-05-01 00:00:00
8  Charlie   0.0        Delhi      M    charlie@example  2021-07-20 00:00:00

In [9]:
df["Age"].fillna(df['Age'].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [10]:
df.ffill() #forward fill

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie  25.0        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
3  Charlie  30.0        Delhi      M    charlie@example 2021-07-20
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5    David  28.0        Delhi      F     eve@domain.com 2019-11-12
6    Alice  25.0     New York      F  alice@example.com 2021-05-01
7    Alice  25.0     New York      F  alice@example.com 2021-05-01
8  Charlie  25.0        Delhi      M    charlie@example 2021-07-20

In [11]:
df.bfill() #backwardfill

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie  30.0        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
3  Charlie  22.0        Delhi      M    charlie@example 2021-07-20
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5    Alice  28.0        Delhi      F     eve@domain.com 2021-05-01
6    Alice  25.0     New York      F  alice@example.com 2021-05-01
7    Alice  25.0     New York      F  alice@example.com 2021-05-01
8  Charlie   NaN        Delhi      M    charlie@example 2021-07-20

In [12]:
#Detecting and removing duplicates
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [13]:
df.drop_duplicates()

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie   NaN        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5      NaN  28.0        Delhi      F     eve@domain.com        NaT

In [14]:
# for prticular columns , we can also check.
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [15]:
df.drop_duplicates(subset=["Name","Age"])

      Name   Age         City Gender              Email  Join Date
0    Alice  25.0     New York      F  alice@example.com 2021-05-01
1  Charlie   NaN        Delhi      M    charlie@example 2021-07-20
2      Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
4    David  22.0       Mumbai      M  david@example.com 2019-11-12
5      NaN  28.0        Delhi      F     eve@domain.com        NaT

In [16]:
#String Operations with .str
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [17]:
df['City'].str.contains("delhi",case=False)  #case=false means case insensitive

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [18]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [19]:
type(df["Email"].str.split("@")[0]) # stores in list

list

In [20]:
#Type conversion usinf .astype()
df2=df.dropna().copy()

In [21]:
df2

    Name   Age         City Gender              Email  Join Date
0  Alice  25.0     New York      F  alice@example.com 2021-05-01
2    Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
4  David  22.0       Mumbai      M  david@example.com 2019-11-12
6  Alice  25.0     New York      F  alice@example.com 2021-05-01
7  Alice  25.0     New York      F  alice@example.com 2021-05-01

In [22]:
df2["Age"]=df2["Age"].astype(int)

In [23]:
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-11-12
6  Alice   25     New York      F  alice@example.com 2021-05-01
7  Alice   25     New York      F  alice@example.com 2021-05-01

In [24]:
# Applying functions
df2["Age Group"] = df['Age'].apply(lambda x: "Adult" if x>27 else "Minor")

In [25]:
df2

    Name  Age         City Gender              Email  Join Date Age Group
0  Alice   25     New York      F  alice@example.com 2021-05-01     Minor
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai      M  david@example.com 2019-11-12     Minor
6  Alice   25     New York      F  alice@example.com 2021-05-01     Minor
7  Alice   25     New York      F  alice@example.com 2021-05-01     Minor

In [26]:
gender_map = {"M": "Male", "F": "Female"}
df2["Gender"]=df2["Gender"].map(gender_map)

In [27]:
df2

    Name  Age         City  Gender              Email  Join Date Age Group
0  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor
2    Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai    Male  david@example.com 2019-11-12     Minor
6  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor
7  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor

In [28]:
df2["City"]=df2["City"].replace({"Delhi": "New Delhi", "Mumbai": " New Mumbai"})

In [29]:
df2

    Name  Age         City  Gender              Email  Join Date Age Group
0  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor
2    Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
4  David   22   New Mumbai    Male  david@example.com 2019-11-12     Minor
6  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor
7  Alice   25     New York  Female  alice@example.com 2021-05-01     Minor